//! C-P6 verify step: **full `UseHint`** as a Plonky3 AIR — FIPS-204 `Decompose` (with the
//! centered remainder + the `r−r0 == q−1` boundary) composed with the hint's `±1 mod 16`
//! adjustment, for ML-DSA-87 (`γ2=(q−1)/32`, `2γ2=523776`, `m=(q−1)/(2γ2)=16`). This is the
//! step that reconstructs `w1` in `Verify`; the earlier `decompose_air.rs` proved only the
//! uncentered Euclidean split, so this AIR proves the full, verify-accurate `UseHint`.
//!
//! Traces are generated by the SAME reference `decompose`/`use_hint` that `mldsa_verify_ref.rs`
//! runs (validated: that verify AGREES with libcrux on 48 cases), and the AIR's `W1` column is
//! diff-tested against it. `--corrupt` perturbs the trace → rejected.

use p3_air::{Air, AirBuilder, BaseAir, WindowAccess};
use p3_baby_bear::{BabyBear, Poseidon2BabyBear, default_babybear_poseidon2_16};
use p3_challenger::DuplexChallenger;
use p3_commit::ExtensionMmcs;
use p3_dft::Radix2DitParallel;
use p3_field::extension::BinomialExtensionField;
use p3_field::{Field, PrimeCharacteristicRing, PrimeField64};
use p3_fri::{FriParameters, TwoAdicFriPcs};
use p3_matrix::dense::RowMajorMatrix;
use p3_merkle_tree::MerkleTreeMmcs;
use p3_symmetric::{PaddingFreeSponge, TruncatedPermutation};
use p3_uni_stark::{StarkConfig, prove, verify};

const Q: i64 = 8380417;
const GAMMA2: i64 = (Q - 1) / 32; // 261888
const G2: i64 = 2 * GAMMA2; // 523776
const MM: i64 = 16; // (q-1)/(2γ2)

// primary field columns
const R: usize = 0;
const H: usize = 1;
const R1U: usize = 2;
const R0U: usize = 3;
const HI: usize = 4;
const T_HI: usize = 5; // slack forcing HI = [r0u > γ2]
const BND: usize = 6;
const WINV: usize = 7; // (R1C-16)^{-1} witness
const R1D: usize = 8; // r1_dec (0 if boundary else r1c)
const NZ0: usize = 9; // [r0u != 0]
const NZ0INV: usize = 10;
const TMP: usize = 11; // (1-HI)(1-BND)
const R0POS: usize = 12; // [centered r0 (post-boundary) > 0]
const WP: usize = 13; // [R1D == 15]
const WPINV: usize = 14;
const WM: usize = 15; // [R1D == 0]
const WMINV: usize = 16;
const ADJP: usize = 17;
const ADJM: usize = 18;
const W1: usize = 19;
const GR: usize = 20; // q-1-R
const GR0U: usize = 21; // g2-1-R0U
const GR1U: usize = 22; // 16-R1U
const NP: usize = 23;
// bit-ranged columns (widths); flags/inverses are not bit-ranged.
const RANGED: [(usize, usize); 8] =
    [(R, 23), (R0U, 20), (R1U, 5), (T_HI, 20), (R1D, 4), (W1, 4), (GR, 23), (GR0U, 20)];
const GR1U_W: usize = 5;
const NUM_COLS: usize = NP + 23 + 20 + 5 + 20 + 4 + 4 + 23 + 20 + 5; // NP + sum widths + GR1U

fn ranged_off(idx: usize) -> usize {
    NP + RANGED[..idx].iter().map(|&(_, w)| w).sum::<usize>()
}
fn gr1u_off() -> usize {
    NP + RANGED.iter().map(|&(_, w)| w).sum::<usize>()
}

struct UseHintAir {}

impl<F> BaseAir<F> for UseHintAir {
    fn width(&self) -> usize {
        NUM_COLS
    }
    fn num_public_values(&self) -> usize {
        0
    }
    fn max_constraint_degree(&self) -> Option<usize> {
        Some(3)
    }
}

impl<AB: AirBuilder> Air<AB> for UseHintAir {
    fn eval(&self, builder: &mut AB) {
        let main = builder.main();
        let row = main.current_slice();
        let one = AB::Expr::ONE;
        let e = |i: usize| -> AB::Expr { row[i].into() };
        let bit = |b: &AB::Expr, builder: &mut AB| builder.assert_zero(b.clone() * (b.clone() - one.clone()));

        // range-check the bit-decomposed columns.
        for (ri, &(col, w)) in RANGED.iter().enumerate() {
            let bo = ranged_off(ri);
            let mut acc = AB::Expr::ZERO;
            let mut wt = AB::Expr::ONE;
            for j in 0..w {
                let b: AB::Expr = row[bo + j].into();
                bit(&b, builder);
                acc = acc + b * wt.clone();
                wt = wt.clone() + wt.clone();
            }
            builder.assert_eq(e(col), acc);
        }
        {
            let bo = gr1u_off();
            let mut acc = AB::Expr::ZERO;
            let mut wt = AB::Expr::ONE;
            for j in 0..GR1U_W {
                let b: AB::Expr = row[bo + j].into();
                bit(&b, builder);
                acc = acc + b * wt.clone();
                wt = wt.clone() + wt.clone();
            }
            builder.assert_eq(e(GR1U), acc);
        }
        // flags boolean
        for &f in &[H, HI, BND, NZ0, R0POS, WP, WM] {
            let b = e(f);
            bit(&b, builder);
        }

        let g2 = AB::Expr::from_u64(G2 as u64);
        let gamma2 = AB::Expr::from_u64(GAMMA2 as u64);
        let sixteen = AB::Expr::from_u64(16);

        // (1) uncentered split: r = r1u·g2 + r0u  (exact, r1u·g2 ≤ q-1 < p).
        builder.assert_eq(e(R), e(R1U) * g2.clone() + e(R0U));
        // canonical bounds.
        builder.assert_eq(e(R) + e(GR), AB::Expr::from_u64((Q - 1) as u64));
        builder.assert_eq(e(R0U) + e(GR0U), AB::Expr::from_u64((G2 - 1) as u64));
        builder.assert_eq(e(R1U) + e(GR1U), sixteen.clone());

        // (2) HI = [r0u > γ2]: r0u − γ2 − 1 + (1−HI)·g2 = T_HI ∈ [0,g2).
        builder.assert_eq(e(R0U) - gamma2 - one.clone() + (one.clone() - e(HI)) * g2, e(T_HI));

        // r1c = r1u + hi  (expression).
        let r1c = e(R1U) + e(HI);
        // (3) BND = [r1c == 16]: is-zero of (r1c − 16).
        builder.assert_zero(e(BND) * (r1c.clone() - sixteen.clone()));
        builder.assert_eq((r1c.clone() - sixteen.clone()) * e(WINV), one.clone() - e(BND));
        // (4) r1_dec = r1c·(1 − BND).
        builder.assert_eq(e(R1D), r1c.clone() - r1c.clone() * e(BND));

        // (5) NZ0 = [r0u != 0].
        builder.assert_eq(e(R0U) * e(NZ0INV), e(NZ0));
        builder.assert_zero((one.clone() - e(NZ0)) * e(R0U));
        // (6) R0POS = (1−HI)·(1−BND)·NZ0  (post-boundary centered r0 > 0).
        builder.assert_eq(e(TMP), (one.clone() - e(HI)) * (one.clone() - e(BND)));
        builder.assert_eq(e(R0POS), e(TMP) * e(NZ0));

        // (7) wrap flags: WP=[r1d==15], WM=[r1d==0].
        builder.assert_zero(e(WP) * (e(R1D) - AB::Expr::from_u64(15)));
        builder.assert_eq((e(R1D) - AB::Expr::from_u64(15)) * e(WPINV), one.clone() - e(WP));
        builder.assert_zero(e(WM) * e(R1D));
        builder.assert_eq(e(R1D) * e(WMINV), one.clone() - e(WM));

        // (8) hint adjustment, flattened to degree ≤ 3:
        //   ADJP = R0POS·(1 − 16·WP)          (+1 with mod-16 wrap when r1d==15)
        //   ADJM = (1−R0POS)·(−1 + 16·WM)     (−1 with mod-16 wrap when r1d==0)
        //   W1 = R1D + H·(ADJP + ADJM)
        builder.assert_eq(e(ADJP), e(R0POS) * (one.clone() - sixteen.clone() * e(WP)));
        builder.assert_eq(e(ADJM), (one.clone() - e(R0POS)) * (sixteen.clone() * e(WM) - one.clone()));
        builder.assert_eq(e(W1), e(R1D) + e(H) * (e(ADJP) + e(ADJM)));
    }
}

// ---- reference (identical to mldsa_verify_ref.rs) ----
fn decompose(r: i64) -> (i64, i64) {
    let r = r.rem_euclid(Q);
    let mut r0 = r % G2;
    if r0 > GAMMA2 {
        r0 -= G2;
    }
    if r - r0 == Q - 1 { (0, r0 - 1) } else { ((r - r0) / G2, r0) }
}
fn use_hint(h: bool, r: i64) -> i64 {
    let (r1, r0) = decompose(r);
    if h {
        if r0 > 0 { (r1 + 1).rem_euclid(MM) } else { (r1 - 1).rem_euclid(MM) }
    } else {
        r1
    }
}

fn inv(x: i64) -> i64 {
    // field inverse mod BabyBear p for the is-zero witnesses.
    let p: i64 = 2013265921;
    let x = x.rem_euclid(p);
    if x == 0 {
        return 0;
    }
    let (mut a, mut b, mut u, mut v) = (x, p, 1i64, 0i64);
    while a != 0 {
        let q = b / a;
        (a, b) = (b - q * a, a);
        (u, v) = (v - q * u, u);
    }
    v.rem_euclid(p)
}

fn generate<F: PrimeField64>(data: &[(i64, bool)]) -> RowMajorMatrix<F> {
    let n = data.len();
    assert!(n.is_power_of_two());
    let mut vals = F::zero_vec(n * NUM_COLS);
    let put_bits = |vals: &mut [F], base: usize, off: usize, v: u64, w: usize| {
        for j in 0..w {
            vals[base + off + j] = F::from_u64((v >> j) & 1);
        }
    };
    for (idx, &(r, h)) in data.iter().enumerate() {
        let base = idx * NUM_COLS;
        let r = r.rem_euclid(Q);
        let r1u = r / G2;
        let r0u = r % G2;
        let hi = (r0u > GAMMA2) as i64;
        let r1c = r1u + hi;
        let bnd = (r1c == 16) as i64;
        let r1d = if bnd == 1 { 0 } else { r1c };
        let nz0 = (r0u != 0) as i64;
        let tmp = (1 - hi) * (1 - bnd);
        let r0pos = tmp * nz0;
        let wp = (r1d == 15) as i64;
        let wm = (r1d == 0) as i64;
        let adjp = r0pos * (1 - 16 * wp);
        let adjm = (1 - r0pos) * (16 * wm - 1);
        let w1 = r1d + (h as i64) * (adjp + adjm);
        // sanity: matches the reference use_hint.
        assert_eq!(w1, use_hint(h, r), "usehint mismatch r={r} h={h}");

        let set = |vals: &mut [F], c: usize, v: i64| vals[base + c] = F::from_u64(v.rem_euclid(Q) as u64);
        set(&mut vals, R, r);
        vals[base + H] = F::from_u64(h as u64);
        set(&mut vals, R1U, r1u);
        set(&mut vals, R0U, r0u);
        vals[base + HI] = F::from_u64(hi as u64);
        let t_hi = r0u - GAMMA2 - 1 + (1 - hi) * G2;
        set(&mut vals, T_HI, t_hi);
        vals[base + BND] = F::from_u64(bnd as u64);
        vals[base + WINV] = F::from_u64(inv(r1c - 16) as u64);
        set(&mut vals, R1D, r1d);
        vals[base + NZ0] = F::from_u64(nz0 as u64);
        vals[base + NZ0INV] = F::from_u64(inv(r0u) as u64);
        // signed intermediates (ADJP/ADJM can be negative) must be reduced mod the FIELD
        // prime p, not mod q, so the column matches the field-arithmetic constraint.
        const P: i64 = 2013265921;
        vals[base + TMP] = F::from_u64(tmp.rem_euclid(P) as u64);
        vals[base + R0POS] = F::from_u64(r0pos as u64);
        vals[base + WP] = F::from_u64(wp as u64);
        vals[base + WPINV] = F::from_u64(inv(r1d - 15) as u64);
        vals[base + WM] = F::from_u64(wm as u64);
        vals[base + WMINV] = F::from_u64(inv(r1d) as u64);
        vals[base + ADJP] = F::from_u64(adjp.rem_euclid(P) as u64);
        vals[base + ADJM] = F::from_u64(adjm.rem_euclid(P) as u64);
        set(&mut vals, W1, w1);
        set(&mut vals, GR, Q - 1 - r);
        set(&mut vals, GR0U, G2 - 1 - r0u);
        set(&mut vals, GR1U, 16 - r1u);
        // bit decomps for ranged columns
        for (ri, &(_, w)) in RANGED.iter().enumerate() {
            let v = vals[base + RANGED[ri].0].as_canonical_u64();
            put_bits(&mut vals, base, ranged_off(ri), v, w);
        }
        put_bits(&mut vals, base, gr1u_off(), (16 - r1u) as u64, GR1U_W);
    }
    RowMajorMatrix::new(vals, NUM_COLS)
}

type Val = BabyBear;
type Perm = Poseidon2BabyBear<16>;
type MyHash = PaddingFreeSponge<Perm, 16, 8, 8>;
type MyCompress = TruncatedPermutation<Perm, 2, 8, 16>;
type ValMmcs = MerkleTreeMmcs<<Val as Field>::Packing, <Val as Field>::Packing, MyHash, MyCompress, 2, 8>;
type Challenge = BinomialExtensionField<Val, 4>;
type ChallengeMmcs = ExtensionMmcs<Val, Challenge, ValMmcs>;
type Challenger = DuplexChallenger<Val, Perm, 16, 8>;
type Dft = Radix2DitParallel<Val>;
type Pcs = TwoAdicFriPcs<Val, Dft, ValMmcs, ChallengeMmcs>;
type MyConfig = StarkConfig<Pcs, Challenge, Challenger>;

fn make_config() -> MyConfig {
    let perm = default_babybear_poseidon2_16();
    let hash = MyHash::new(perm.clone());
    let compress = MyCompress::new(perm.clone());
    let val_mmcs = ValMmcs::new(hash, compress, 0);
    let challenge_mmcs = ChallengeMmcs::new(val_mmcs.clone());
    let dft = Dft::default();
    let fri_params = FriParameters {
        log_blowup: 2,
        log_final_poly_len: 0,
        max_log_arity: 1,
        num_queries: 8,
        commit_proof_of_work_bits: 1,
        query_proof_of_work_bits: 1,
        mmcs: challenge_mmcs,
    };
    let pcs = Pcs::new(dft, val_mmcs, fri_params);
    let challenger = Challenger::new(perm);
    MyConfig::new(pcs, challenger)
}

fn main() {
    let corrupt = std::env::args().any(|a| a == "--corrupt");
    let air = UseHintAir {};
    // 16 (r, h) cases: boundaries (0, γ2, γ2+1, q-1), interior, both hint values.
    let data: Vec<(i64, bool)> = vec![
        (0, false), (0, true),
        (GAMMA2, false), (GAMMA2, true),
        (GAMMA2 + 1, false), (GAMMA2 + 1, true),
        (G2, false), (G2, true),
        (5 * G2 + 12345, false), (5 * G2 + 12345, true),
        (Q - 1, false), (Q - 1, true),
        (Q - 2, false), (Q - 2, true),
        (G2 + GAMMA2, false), (G2 + GAMMA2, true),
    ];
    let mut trace = generate::<Val>(&data);
    if corrupt {
        trace.values[W1] += Val::ONE; // wrong UseHint output for row 0
    }
    let config = make_config();
    let pis: Vec<Val> = vec![];
    let proof = prove(&config, &air, trace, &pis);
    match verify(&config, &air, &proof, &pis) {
        Ok(_) if corrupt => println!("NEGATIVE TEST FAIL — corrupt UseHint trace accepted!"),
        Ok(_) => println!(
            "VERIFY ok — full ML-DSA-87 UseHint proven as a Plonky3 AIR: FIPS-204 Decompose (centered r0 + r−r0==q−1 boundary) + hint ±1 mod 16, over 16 (r,h) cases incl. boundaries. W1 column diff-tested == reference use_hint (== mldsa_verify_ref.rs, which agrees with libcrux). --corrupt rejected. This completes the verify-step gadget layer (only the AIR wiring/tiling remains)."
        ),
        Err(e) if corrupt => println!("NEGATIVE TEST PASS — corrupt UseHint trace rejected: {e:?}"),
        Err(e) => println!("UNEXPECTED reject on a valid trace: {e:?}"),
    }
}
